#!/usr/bin/env node

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const part = argv[i];
    if (!part.startsWith("--")) {
      continue;
    }
    const key = part.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith("--")) {
      args[key] = true;
      continue;
    }
    args[key] = next;
    i += 1;
  }
  return args;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function sqlQuote(value) {
  if (value == null) {
    return "NULL";
  }
  const normalized = String(value).replace(/'/g, "''");
  return `'${normalized}'`;
}

function jsonSql(value) {
  return `CAST(${sqlQuote(JSON.stringify(value))} AS JSON)`;
}

function hashPayload(value) {
  return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
}

function toCharCount(value) {
  return Array.from(String(value || "")).length;
}

function loadParsedReports(parsedDir) {
  const parsedReports = new Map();
  if (!fs.existsSync(parsedDir)) {
    return parsedReports;
  }

  const files = fs
    .readdirSync(parsedDir)
    .filter((fileName) => fileName.endsWith(".json"))
    .sort();

  for (const fileName of files) {
    const filePath = path.join(parsedDir, fileName);
    const parsed = readJson(filePath);
    parsed.__parsed_file_path = filePath;
    const report = parsed.meta && parsed.meta.report ? parsed.meta.report : null;
    if (report && report.item_key) {
      parsedReports.set(report.item_key, parsed);
    }
  }

  return parsedReports;
}

function buildChunkRows(sourceItem, parsedReport) {
  if (!parsedReport || !Array.isArray(parsedReport.chunk_previews)) {
    return [];
  }

  return parsedReport.chunk_previews.map((chunk, index) => {
    const content = chunk.text_preview || "";
    return {
      chunk_index: index + 1,
      chunk_type: "table",
      heading_path: `${sourceItem.title} / ${chunk.sheet_name}`,
      content,
      char_count: toCharCount(content),
      meta_json: {
        sheet_name: chunk.sheet_name,
        row_count: chunk.row_count,
        header_row_index: chunk.header_row_index,
        headers: chunk.headers,
        sample_rows: chunk.sample_rows,
        parsed_json_file: parsedReport.__parsed_file_path || null,
        source_file:
          parsedReport.meta && parsedReport.meta.input_file
            ? parsedReport.meta.input_file
            : sourceItem.extra_json && sourceItem.extra_json.file_path,
      },
    };
  });
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const distillationDir = args["distillation-dir"] || path.resolve(__dirname, "..");
  const outputDir = args.output || path.join(distillationDir, "output");
  const payloadPath =
    args.payload || path.join(outputDir, "midmax_zhixiao_distill_payload.json");
  const rowsManifestPath =
    args["rows-manifest"] || path.join(outputDir, "midmax_zhixiao_rows_manifest.json");
  const parsedDir = args["parsed-dir"] || path.join(outputDir, "parsed_reports");
  const sqlPath =
    args["sql-path"] || path.join(outputDir, "midmax_zhixiao_import.sql");

  ensureDir(outputDir);

  const payload = readJson(payloadPath);
  const rowsManifest = fs.existsSync(rowsManifestPath) ? readJson(rowsManifestPath) : { reports: [] };
  const parsedReportsByItemKey = loadParsedReports(parsedDir);
  const rawRecordByFilePath = new Map();

  for (const rawRecord of payload.raw_records || []) {
    const filePath = rawRecord.raw_payload_json && rawRecord.raw_payload_json.file_path;
    if (filePath) {
      rawRecordByFilePath.set(filePath, rawRecord);
    }
  }

  const lines = [];
  lines.push("-- Auto generated by generate_mysql_import_sql.js");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push("USE relation_ai_distill;");
  lines.push("START TRANSACTION;");
  lines.push("");

  const sourceConfig = payload.source_config;
  const syncJob = payload.sync_job;
  const parsedCount = rowsManifest.reports.filter((report) => report.status === "parsed").length;

  lines.push("-- 1. Upsert data source");
  lines.push(
    [
      "INSERT INTO ai_data_sources (",
      "  source_code, source_name, source_type, source_origin, access_method,",
      "  endpoint, sync_frequency, status, config_json, created_at, updated_at",
      ") VALUES (",
      `  ${sqlQuote(sourceConfig.source_code)},`,
      `  ${sqlQuote(sourceConfig.source_name)},`,
      `  ${sqlQuote(sourceConfig.source_type)},`,
      `  ${sqlQuote(sourceConfig.source_origin)},`,
      `  ${sqlQuote(sourceConfig.access_method)},`,
      `  ${sqlQuote(sourceConfig.endpoint)},`,
      `  ${sqlQuote(sourceConfig.sync_frequency)},`,
      `  ${sqlQuote(sourceConfig.status)},`,
      `  ${jsonSql(sourceConfig.config_json)},`,
      "  NOW(3), NOW(3)",
      ")",
      "ON DUPLICATE KEY UPDATE",
      "  source_name = VALUES(source_name),",
      "  source_type = VALUES(source_type),",
      "  source_origin = VALUES(source_origin),",
      "  access_method = VALUES(access_method),",
      "  endpoint = VALUES(endpoint),",
      "  sync_frequency = VALUES(sync_frequency),",
      "  status = VALUES(status),",
      "  config_json = VALUES(config_json),",
      "  updated_at = NOW(3);",
      "",
      `SET @source_id = (SELECT id FROM ai_data_sources WHERE source_code = ${sqlQuote(
        sourceConfig.source_code
      )} LIMIT 1);`,
      "",
      "-- 2. Insert sync job",
      "INSERT INTO ai_source_sync_jobs (",
      "  source_id, job_type, trigger_mode, window_start, window_end, status,",
      "  raw_count, normalized_count, run_log_json, started_at, finished_at, created_at, updated_at",
      ") VALUES (",
      "  @source_id,",
      `  ${sqlQuote(syncJob.job_type)},`,
      `  ${sqlQuote(syncJob.trigger_mode)},`,
      `  ${sqlQuote(`${payload.meta.date_range.start} 00:00:00`)},`,
      `  ${sqlQuote(`${payload.meta.date_range.end} 23:59:59`)},`,
      "  'success',",
      `  ${Number(syncJob.raw_count || 0)},`,
      `  ${Number(parsedCount)},`,
      `  ${jsonSql(syncJob.run_log_json)},`,
      "  NOW(3),",
      "  NOW(3),",
      "  NOW(3),",
      "  NOW(3)",
      ");",
      "SET @sync_job_id = LAST_INSERT_ID();",
      "",
    ].join("\n")
  );

  lines.push("-- 3. Upsert raw records, source items, and preview chunks");
  for (const sourceItem of payload.source_items || []) {
    const inputFile = sourceItem.extra_json && sourceItem.extra_json.file_path;
    const rawRecord = rawRecordByFilePath.get(inputFile);
    if (!rawRecord) {
      continue;
    }

    const payloadHash = hashPayload(rawRecord.raw_payload_json);
    const parsedReport = parsedReportsByItemKey.get(sourceItem.item_key);
    const chunks = buildChunkRows(sourceItem, parsedReport);

    lines.push(`-- ${sourceItem.title}`);
    lines.push(
      [
        "INSERT INTO ai_raw_records (",
        "  source_id, sync_job_id, source_record_key, raw_type, content_type, title, raw_text,",
        "  raw_payload_json, payload_hash, happened_at, captured_at, created_at, updated_at",
        ") VALUES (",
        "  @source_id,",
        "  @sync_job_id,",
        `  ${sqlQuote(rawRecord.source_record_key)},`,
        `  ${sqlQuote(rawRecord.raw_type)},`,
        `  ${sqlQuote(rawRecord.content_type)},`,
        `  ${sqlQuote(rawRecord.title)},`,
        "  NULL,",
        `  ${jsonSql(rawRecord.raw_payload_json)},`,
        `  ${sqlQuote(payloadHash)},`,
        `  ${sqlQuote(rawRecord.happened_at)},`,
        "  NOW(3),",
        "  NOW(3),",
        "  NOW(3)",
        ")",
        "ON DUPLICATE KEY UPDATE",
        "  sync_job_id = VALUES(sync_job_id),",
        "  raw_type = VALUES(raw_type),",
        "  content_type = VALUES(content_type),",
        "  title = VALUES(title),",
        "  raw_payload_json = VALUES(raw_payload_json),",
        "  payload_hash = VALUES(payload_hash),",
        "  happened_at = VALUES(happened_at),",
        "  captured_at = NOW(3),",
        "  updated_at = NOW(3);",
        `SET @raw_record_id = (SELECT id FROM ai_raw_records WHERE source_id = @source_id AND source_record_key = ${sqlQuote(
          rawRecord.source_record_key
        )} LIMIT 1);`,
      ].join("\n")
    );

    lines.push(
      [
        "INSERT INTO ai_source_items (",
        "  source_id, raw_record_id, item_type, item_key, source_module, title, summary,",
        "  source_url, happened_at, published_at, status, tags_json, extra_json, created_at, updated_at",
        ") VALUES (",
        "  @source_id,",
        "  @raw_record_id,",
        `  ${sqlQuote(sourceItem.item_type)},`,
        `  ${sqlQuote(sourceItem.item_key)},`,
        `  ${sqlQuote(sourceItem.source_module)},`,
        `  ${sqlQuote(sourceItem.title)},`,
        `  ${sqlQuote(sourceItem.summary)},`,
        `  ${sqlQuote(sourceItem.source_url)},`,
        `  ${sqlQuote(sourceItem.happened_at)},`,
        `  ${sqlQuote(sourceItem.published_at)},`,
        `  ${sqlQuote(sourceItem.status)},`,
        `  ${jsonSql(sourceItem.tags_json)},`,
        `  ${jsonSql(sourceItem.extra_json)},`,
        "  NOW(3),",
        "  NOW(3)",
        ")",
        "ON DUPLICATE KEY UPDATE",
        "  raw_record_id = VALUES(raw_record_id),",
        "  item_type = VALUES(item_type),",
        "  source_module = VALUES(source_module),",
        "  title = VALUES(title),",
        "  summary = VALUES(summary),",
        "  source_url = VALUES(source_url),",
        "  happened_at = VALUES(happened_at),",
        "  published_at = VALUES(published_at),",
        "  status = VALUES(status),",
        "  tags_json = VALUES(tags_json),",
        "  extra_json = VALUES(extra_json),",
        "  updated_at = NOW(3);",
        `SET @source_item_id = (SELECT id FROM ai_source_items WHERE source_id = @source_id AND item_key = ${sqlQuote(
          sourceItem.item_key
        )} LIMIT 1);`,
      ].join("\n")
    );

    for (const chunk of chunks) {
      lines.push(
        [
          "INSERT INTO ai_source_chunks (",
          "  source_item_id, chunk_index, chunk_type, heading_path, content, token_estimate,",
          "  char_count, start_offset, end_offset, chunk_hash, meta_json, created_at, updated_at",
          ") VALUES (",
          "  @source_item_id,",
          `  ${chunk.chunk_index},`,
          `  ${sqlQuote(chunk.chunk_type)},`,
          `  ${sqlQuote(chunk.heading_path)},`,
          `  ${sqlQuote(chunk.content)},`,
          "  NULL,",
          `  ${chunk.char_count},`,
          "  NULL,",
          "  NULL,",
          `  ${sqlQuote(hashPayload(chunk.content))},`,
          `  ${jsonSql(chunk.meta_json)},`,
          "  NOW(3),",
          "  NOW(3)",
          ")",
          "ON DUPLICATE KEY UPDATE",
          "  chunk_type = VALUES(chunk_type),",
          "  heading_path = VALUES(heading_path),",
          "  content = VALUES(content),",
          "  char_count = VALUES(char_count),",
          "  chunk_hash = VALUES(chunk_hash),",
          "  meta_json = VALUES(meta_json),",
          "  updated_at = NOW(3);",
        ].join("\n")
      );
    }

    lines.push("");
  }

  if (Array.isArray(payload.blocked_reports) && payload.blocked_reports.length > 0) {
    lines.push("-- 4. Blocked reports reference");
    for (const report of payload.blocked_reports) {
      lines.push(
        `-- blocked: [${report.report_seq}] ${report.report_name_cn} | ${report.status} | ${
          report.notes || ""
        } | ${report.source_url || ""}`
      );
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("");

  fs.writeFileSync(sqlPath, `${lines.join("\n")}\n`, "utf8");

  process.stdout.write(
    JSON.stringify(
      {
        ok: true,
        sql_path: sqlPath,
        parsed_report_count: parsedCount,
        source_item_count: (payload.source_items || []).length,
      },
      null,
      2
    )
  );
}

main();
